### ISSUE TITLE
Underscored (`_`) function parameters are not grayed out

### ISSUE THREAD

**Issue by maxxst** [elixir-sublime/elixir-sublime-syntax#42]
I'm using the Dracula ColorScheme with SublimeText 4126 and saw that function parameters with leading underscore are not shown differently than normal parameters.

## Elixir Highlighting
![Screenshot 2022-01-31 at 15 05 51](https://user-images.githubusercontent.com/570654/151808089-4d813e14-7c07-470a-953c-1fbb49efaf79.png)

## ElixirSyntax Highlighting
![Screenshot 2022-01-31 at 15 12 05](https://user-images.githubusercontent.com/570654/151808792-a0c1c0da-2f0d-4bc9-9fdd-14c718df81ae.png)

Is that behavior on purpose?

**Comment by azizk** [comment]
It's kind of on purpose. I can explain more later but the gist is that the `Elixir` package assigns `comment.unused.elixir` to underscore variables in order to achieve the "commented-out-look". `ElixirSyntax` on the other hand uses `variable.parameter.unused.elixir` which is not styled in any of the color schemes afaics. There's actually no official `unused` sub-scope name which is unfortunate.

So a quick solution is to either add a custom sublime-color-scheme file – similar to what's there in the `color-schemes/` folder – or you can override the `ElixirSyntax` package and add the `comment.unused` scope to the unused variable parameter rules.

**Comment by princemaple** [comment]
We might as well just add this scope. It's pretty much a convention in most languages. Or do you prefer normal variables over it? @azizk

**Comment by azizk** [comment]
I'm inclined not to add the `comment.unused` scope because it really doesn't make any sense to use that name in order to achieve a styling purpose. It's just not a comment, let alone an "unused comment". The names should be semantically correct, as far as possible, and based on that the color schemes should style them however they desire.

**Comment by princemaple** [comment]
I'm fairly neutral regarding this issue. Customizing the color scheme is easy enough. Should we add something on readme and close this issue?

**Comment by azizk** [comment]
I was thinking about maybe creating a FAQ.md :)

**Comment by princemaple** [comment]
I think that would lack the visibility. Our readme is light enough, I think it still can take in some addition.

**Comment by azizk** [comment]
Okay, we can put it in there or maybe add a section and a link to the file similar to the changelog. :)

**Comment by princemaple** [comment]
Hi @maxxst could you take a look at #43 and let me know whether it's helpful?

**Comment by maxxst** [comment]
for me that is good enough
